export const PARAMETERS = [
  {
    label: "Turnos",
    value: 0,
    type: "input",
    tooltipText: "Duração do duelo em turnos.",
    engLabel: "Turns",
    engTooltipText: "Turns duration of the duel",
  },
  {
    label: "Ataques Efetivos",
    value: 0,
    type: "label",
    tooltipText:
      "Número de vezes que um monstro oponente foi destruído em posição de ataque.",
    engLabel: "Effective Attacks",
    engTooltipText: "When your monster destroys an opponent's monster that is in attack position",
  },
  {
    label: "Vitórias Defensivas",
    value: 0,
    type: "label",
    tooltipText:
      "Número de vezes que um monstro do jogador não foi destruído em posição de defesa.",
    engLabel: "Defensive Wins",
    engTooltipText: "When your monster in defense mode survives an opponent's monster attack",
  },
  {
    label: "Cartas Viradas para Baixo",
    value: 0,
    type: "label",
    tooltipText: "Número de cartas que o jogador baixou durante o duelo.",
    engLabel: "Face-down Plays",
    engTooltipText: "Number of cards you've played face-down",
  },
  {
    label: "Fusões",
    value: 0,
    type: "label",
    tooltipText: "Número de fusões feitas pelo jogador.",
    engLabel: "Initiate Fusion",
    engTooltipText: "Number of fusions you've made",
  },
  {
    label: "Equipamentos",
    value: 0,
    type: "label",
    tooltipText: "Número de equipamentos usados pelo jogador.",
    engLabel: "Equip Magic",
    engTooltipText: "Number of equip magics you've played",
  },
  {
    label: "Magias",
    value: 0,
    type: "label",
    tooltipText: "Número de magias usadas pelo jogador.",
    engLabel: "Pure Magic",
    engTooltipText: "Number of pure magics you've played",
  },
  {
    label: "Armadilhas Disparadas",
    engLabel: "Turns",
    engTooltipText: "Turns duration of the duel",
    value: 0,
    type: "label",
    tooltipText: "Número de armadilhas ativadas pelo jogador.",
    engLabel: "Trigger Trap",
    engTooltipText: "Number of traps you've triggered",
  },
  {
    label: "Cartas Restantes",
    value: 35,
    type: "input",
    tooltipText: "Número de cartas restantes no deck do jogador.",
    engLabel: "Remaining Cards",
    engTooltipText: "Remaining cards on player's deck",
  },
  {
    label: "Pontos de Vida",
    value: 8000,
    type: "input",
    tooltipText: "Pontos de vida restantes ao fim do duelo.",
    engLabel: "Remaining Life Points",
    engTooltipText: "Player's remainig LP",
  },
];
